import { useState } from 'react';
import { Alert, Badge, Button, Card, DashboardShell, Input, PricingCard, SectionHeader } from '@quembi-ui/react';
import type { CatalogItem } from '../data/catalog';

export function Preview({ item, expanded = false }: { item: CatalogItem; expanded?: boolean }) {
  const [clicked, setClicked] = useState(false);
  if (item.plan === 'premium') return <PremiumPreview id={item.id} expanded={expanded} />;
  const compact = !expanded;
  switch (item.id) {
    case 'button': return <div className="flex flex-wrap items-center justify-center gap-2"><Button size={compact ? 'sm' : 'md'} onClick={() => setClicked(v => !v)}>{clicked ? 'Concluído ✓' : 'Criar projecto'}</Button><Button size={compact ? 'sm' : 'md'} variant="outline" onClick={() => setClicked(false)}>Cancelar</Button><Button size="sm" variant="ghost">Mais</Button></div>;
    case 'badge': return <div className="flex flex-wrap items-center justify-center gap-2"><Badge tone="success" dot>Publicado</Badge><Badge tone="violet">Novo</Badge><Badge tone="warning">Pendente</Badge></div>;
    case 'card': return <Card elevated className="mx-auto w-full max-w-[255px] p-4"><div className="mb-4 flex size-9 items-center justify-center rounded-xl bg-violet-100 text-violet-600">✦</div><p className="text-sm font-bold">Workspace Pro</p><p className="mt-1 text-xs text-slate-500">O teu espaço criativo.</p><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-3"><Badge tone="success" dot>Activo</Badge><span className="text-xs font-semibold text-violet-700">Abrir ↗</span></div></Card>;
    case 'input': return <div className="mx-auto w-full max-w-[255px]"><Input label="Endereço de e-mail" type="email" placeholder="nome@empresa.com" hint="Nunca partilharemos o teu e-mail." /></div>;
    case 'alert': return <div className="mx-auto w-full max-w-[300px]"><Alert tone="success" title="Tudo pronto!">As alterações foram guardadas com sucesso.</Alert></div>;
    case 'section-header': return <div className="mx-auto w-full max-w-[340px]"><SectionHeader eyebrow="Workspace" title="Os teus projectos" description="Tudo organizado num só lugar." action={<Button size="sm">+ Novo</Button>} /></div>;
    case 'pricing-card': return <div className="mx-auto w-full max-w-[245px]"><PricingCard className="p-4" name="Starter" price="Grátis" description="Para começar a criar." features={['Componentes essenciais', 'Código aberto']} actionLabel="Experimentar" onAction={() => setClicked(true)} footer={clicked && <p role="status" className="mt-2 text-center text-xs text-emerald-700">Plano seleccionado!</p>} /></div>;
    case 'dashboard-shell': return <div className="mx-auto w-full max-w-[440px]"><DashboardShell className="min-h-[190px] text-[11px] md:grid-cols-[130px_1fr]" brand={<span className="text-sm">◈ Studio</span>} links={[{label: 'Visão geral', href: '#catalogo', active: true}, {label: 'Projectos', href: '#catalogo'}]} header={<span className="text-xs font-semibold">Visão geral</span>}><div className="grid grid-cols-2 gap-2"><div className="rounded-lg bg-white p-3 text-[10px]">Visualizações<br/><b className="text-base">12.4k</b></div><div className="rounded-lg bg-white p-3 text-[10px]">Conversão<br/><b className="text-base">8.2%</b></div></div></DashboardShell></div>;
    default: return null;
  }
}
function PremiumPreview({ id, expanded }: { id: string; expanded: boolean }) {
  if (id === 'analytics') return <div className="w-full max-w-[350px] rounded-xl border border-slate-200 bg-white p-3 shadow-xl shadow-violet-900/5"><div className="mb-3 flex items-center justify-between"><div><p className="text-[10px] text-slate-400">RECEITA TOTAL</p><p className="text-xl font-bold text-slate-900">24.680 Kz <span className="text-[9px] text-emerald-600">↑ 12.8%</span></p></div><div className="rounded-lg bg-violet-100 px-2 py-1 text-[9px] text-violet-700">Este mês⌄</div></div><div className="relative flex h-20 items-end justify-around overflow-hidden rounded-lg bg-violet-50/50 px-2 pt-3">{[28,48,37,67,55,74,62,85,68,96,82,100].map((h,i)=><div key={i} style={{height:`${h}%`}} className="w-[5%] rounded-t bg-gradient-to-t from-violet-600 to-violet-300"/>)}</div><div className="mt-2 flex justify-between text-[9px] text-slate-400"><span>Jan</span><span>Mar</span><span>Mai</span><span>Jul</span><span>Set</span></div></div>;
  if (id === 'commerce') return <div className="flex w-full max-w-[345px] gap-3 rounded-xl border border-slate-200 bg-white p-3 shadow-lg"><div className="flex w-12 flex-col gap-3 rounded-lg bg-slate-900 p-2 text-center text-xs text-white"><span>◈</span><span className="text-violet-300">▦</span><span>▤</span><span>◷</span></div><div className="min-w-0 flex-1"><div className="mb-3 flex justify-between text-xs font-bold text-slate-900"><span>Produtos</span><span className="text-violet-600">+ Novo</span></div>{['Minimal lamp', 'Studio chair', 'Ceramic vase'].map((p,i)=><div key={p} className="mb-2 flex items-center gap-2 rounded-md border border-slate-100 p-1.5"><div className={['bg-amber-100','bg-lime-100','bg-purple-100'][i]+' flex size-7 items-center justify-center rounded text-sm text-slate-700'}>{['◈','▰','◉'][i]}</div><span className="min-w-0 flex-1 truncate text-[10px] text-slate-700">{p}</span><span className="text-[9px] text-emerald-600">Activo</span></div>)}</div></div>;
  if (id === 'auth') return <div className="flex w-full max-w-[340px] overflow-hidden rounded-xl border border-slate-200 bg-white shadow-lg"><div className="hidden w-[40%] flex-col justify-between bg-[#291d55] p-4 text-white sm:flex"><span className="text-sm">✳</span><p className="text-sm font-semibold">O teu melhor trabalho começa aqui.</p><span className="text-[9px] text-violet-200">QUEMBI STUDIO</span></div><div className="flex-1 p-4"><p className="text-sm font-bold text-slate-900">Bem-vindo de volta</p><p className="mt-1 text-[9px] text-slate-400">Inicia sessão na tua conta</p><div className="mt-4 rounded-md border border-slate-200 px-2 py-1.5 text-[9px] text-slate-400">E-mail</div><div className="mt-2 rounded-md border border-slate-200 px-2 py-1.5 text-[9px] text-slate-400">Palavra-passe</div><div className="mt-3 rounded-md bg-violet-600 py-2 text-center text-[9px] font-semibold text-white">Entrar na conta</div></div></div>;
  return <div className="w-full max-w-[350px] overflow-hidden rounded-xl border border-slate-200 bg-[#19162c] p-5 text-white shadow-lg"><div className="flex items-center justify-between text-[10px]"><span className="font-semibold">◈ orbit.</span><span className="rounded-full bg-white px-2 py-1 font-semibold text-slate-900">Get started ↗</span></div><p className="mt-7 text-[9px] font-semibold uppercase tracking-widest text-violet-300">A NEW WAY TO CREATE</p><p className={expanded ? 'mt-2 text-3xl font-bold leading-tight' : 'mt-2 text-2xl font-bold leading-tight'}>Ideas deserve<br/><span className="text-violet-300">better tools.</span></p><p className="mt-2 text-[10px] text-slate-300">Build the next big thing, beautifully.</p><div className="mt-4 flex gap-2"><span className="rounded-md bg-violet-400 px-3 py-1.5 text-[9px] font-semibold text-slate-950">Start creating →</span><span className="rounded-md border border-white/20 px-3 py-1.5 text-[9px]">Explore</span></div></div>;
}
